// <auto-generated />
using HotelListing2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220608094455_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelListing2.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Damascus",
                            ShortName = "DM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lattakia",
                            ShortName = "LT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tartus",
                            ShortName = "TR"
                        });
                });

            modelBuilder.Entity("HotelListing2.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Omaween Square",
                            CountryId = 1,
                            Name = "Dama Rose",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "10th Street",
                            CountryId = 2,
                            Name = "Meredian",
                            Rating = 3.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Address = "Tartus-Homs Highway",
                            CountryId = 3,
                            Name = "Holiday Beach",
                            Rating = 2.8999999999999999
                        },
                        new
                        {
                            Id = 4,
                            Address = "DownTown",
                            CountryId = 1,
                            Name = "Sheraton",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("HotelListing2.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing2.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
